#5 - tsx runtime to invoke source code
ubiquity/action-conventional-commits pull request #9
Opened 2023-07-27 14:59 UTC by PhantomCracker

Resolve #7

2023-07-27 15:00 UTC, PhantomCracker commented
@rndquu please check this and let me know if it works on prod: https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace

2023-07-27 17:12 UTC, pavlovcik commented
> @rndquu please check this and let me know if it works on prod: https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace

The first thing the link says is to use yarn so why dont you try that?

Also can you try using a shell script? It still makes zero sense to me that you can't use a shell script directly.

2023-07-27 20:55 UTC, rndquu commented
> @rndquu please check this and let me know if it works on prod: https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace

Did you try how it works in your forked repo?

2023-07-28 08:44 UTC, PhantomCracker commented
> > @rndquu please check this and let me know if it works on prod: https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace
> 
> Did you try how it works in your forked repo?

These are the tests on my side: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5689595690/job/15421394620
Please notice that on my side was working with npm too

2023-07-28 09:27 UTC, rndquu commented
> > > @rndquu please check this and let me know if it works on prod: https://stackoverflow.com/questions/69220042/npm-err-unsupported-url-type-workspace-workspace
> > 
> > 
> > Did you try how it works in your forked repo?
> 
> These are the tests on my side: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5689595690/job/15421394620 Please notice that on my side was working with npm too

I'm getting this [error](https://github.com/rndquu/ubiquity-dollar/actions/runs/5690394676/job/15423644958)

Your latest conventional commits CI run in the `master` branch [throws](https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5689730056/job/15421778053) the same error

Pls fix the `master` branch

2023-07-28 09:34 UTC, PhantomCracker commented
Yes, that was because I was trying to do something with SH file, but it looks like the emacs doesn't know where and what the yarn is :)
here is the latest test: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5690465733

2023-07-28 09:49 UTC, rndquu commented
> Yes, that was because I was trying to do something with SH file, but it looks like the emacs doesn't know where and what the yarn is :) here is the latest test: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5690465733

I don't really understand why it works in your repo but [fails](https://github.com/rndquu/ubiquity-dollar/actions/runs/5690394676/job/15424158179) in my

2023-07-28 10:52 UTC, PhantomCracker commented
> fails

Ok, good question, let me investigate this and make a fix for it
Be right back with an answer

2023-07-29 08:27 UTC, PhantomCracker commented
Hei @rndquu ,
I was checking what you are testing and now it's clear for me.
If I run the action on the action-conventional-commits repository everything is fine as you can see here: https://github.com/PhantomCracker/action-conventional-commits/actions/runs/5699435599/job/15448346012

BUT, if I run the action in another repository (for example like you did it on ubiquity-dollar), we receive the following error that says that the src/main.ts file does not exist:
<img width="1254" alt="Screenshot 2023-07-29 at 10 55 09" src="https://github.com/ubiquity/action-conventional-commits/assets/5438246/c5778b30-b25d-43a0-8359-0edad6c0ebb0">

So what we need to do is to run all the files in the context of action-conventional-commits repository; to do this we need to run the dist/index.js file :) 
If you have any other idea, please let me know, I will also try new approaches.

2023-07-29 14:04 UTC, rndquu commented
> So what we need to do is to run all the files in the context of action-conventional-commits repository

I don't understand what "run all the files in the context of action-conventional-commits repository" means. Did you manage to run the conventional commits workflow in a 3rd party repo, not in the https://github.com/PhantomCracker/action-conventional-commits ?

2023-07-29 17:31 UTC, PhantomCracker commented
> > So what we need to do is to run all the files in the context of action-conventional-commits repository
> 
> I don't understand what "run all the files in the context of action-conventional-commits repository" means. Did you manage to run the conventional commits workflow in a 3rd party repo, not in the https://github.com/PhantomCracker/action-conventional-commits ?

I mean that as you see in the screenshot that I have shared, the `src/main.ts` is not found in ubiquity dollar repository; basically, this happens because we run the following command in `src/index.js`:
`yes 2>/dev/null | npx tsx src/main.ts`
So we need to keep all the actions in the context of action-conventional-commits repository i think...
And I would like to know if you thinked on something else for this issue

2023-07-31 08:56 UTC, rndquu requested changes
So github supports [JS actions](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action) but they require either using [ncc](https://github.com/vercel/ncc) to compile all dependencies in a single file either commiting the whole `node_modules` folder

There are also [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) which allow to do pretty much everything

If we want to run `tsx` without commiting dependencies we need to: 
- use composite action instead of JS action
- in the action's yml download `action-conventional-commits`, install dependencies and run `tsx`

@PhantomCracker pls refactor [this way](https://github.com/rndquu/action-conventional-commits/blob/ci/composite/action.yml)

2023-07-31 08:56 UTC, rndquu commented on .github/workflows/test.yml
Pls remove this file

2023-07-31 08:56 UTC, rndquu commented on src/index.js
Pls remove this file either along with `dist/main/index.js`

2023-07-31 15:52 UTC, PhantomCracker commented
I see... thank you for explanations, pull request has been updated.

2023-07-31 20:39 UTC, rndquu requested changes

2023-07-31 20:39 UTC, rndquu commented on action.yml
> +      run: cd ~ && git clone https://github.com/rndquu/action-conventional-commits
```suggestion
      run: cd ~ && git clone https://github.com/ubiquity/action-conventional-commits
```

2023-08-01 08:43 UTC, rndquu approved these changes

2023-08-01 08:44 UTC, merged